version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wiki-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wiki
    ports:
      - "5432:5432"
    volumes:
      - wiki-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: wiki-meilisearch
    environment:
      MEILI_MASTER_KEY: "myMasterKey123"
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili-data:/meili_data

volumes:
  wiki-data:
  meili-data:
